
globals:
  logfile: empty.log
  service_module: tkservices

service_objects:
  telekast:
    class: TelekastService
    init_params:
      - name: kafka_nodes
        value:
          - 10.164.0.81
          - 10.164.0.107
          - 10.164.0.31

pipelines:
  test:
    record_format: json
    settings:
    record_header_fields:
      - ingest_timestamp
      - pipeline_name
      - record_type
    record_payload_field: data
