- hosts: k7
  become: true
  vars_files:
    - ansible_vars/kafka-servers.yml

  tasks:
    - name: Create the kafka group
      become_user: root
      group:
        name: kafka

    - name: Create the kafka user      
      become_user: root
      user:
        name: kafka        
        shell: /bin/bash
        system: no
        group: kafka
        state: present

    - name: Test templating            
      debug: 
        msg: "{{ brokers[inventory_hostname] }}"
      
    - name: Populate config template
      become_user: dtaylor
      template:
        src: template_files/server.properties.j2
        dest: ~/server.properties